import { StyleSheet } from 'react-native';
import {deviceHeight,deviceWidth,px} from '../../utils/dimensions';
export default StyleSheet.create({


  container: {
    flex: 1,
    paddingTop: 20,
  },

  backgroundImage: {
  flex: 1,
   width: deviceWidth,
    height: deviceHeight,
},

  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: px(15),
    marginRight: px(19),
    marginLeft: px(10),

  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingRight: px(10),
  },
  profileImg: {
    width: px(40),
    height: px(40),
    borderRadius: px(10),
    marginRight: px(10),
  },
  welcomeText: {
    fontSize: px(12),
    color: '#777',
  },
  userName: {
    fontSize: px(16),
    fontWeight: '600',
    color: '#000',
  },
  iconContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIcon: {
    width: px(25),
    height: px(25),
    marginLeft: px(15),
    tintColor: '#000',
  },
  crownIcon: {
    width: px(20),
    height: px(20),
    tintColor: '#EEA83D',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: px(16),
    paddingHorizontal: px(16),
    paddingVertical: px(10),
    marginBottom: px(15),
    marginLeft: px(15),
    marginRight: px(15),
    borderColor: '#ddd',
    borderWidth: 1,
  },
  searchInput: {
    flex: 1,
    marginLeft: px(8),
    color: '#000',
  },
  tabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: px(10),
       borderRadius: px(6),
  },
  tab: {
    backgroundColor: '#fff',
    paddingVertical: px(6),
    paddingHorizontal: px(12),
    borderRadius: px(8),
    borderWidth: 1,
    borderColor: '#686868',
  },
  tabActive: {
    backgroundColor: '#FF984F',
    paddingVertical: px(6),
    paddingHorizontal: px(12),
    borderRadius: px(8),
  },
  tabText: {
    fontSize: px(16),
    color: '#2F2F2F',
     fontWeight: '500',
  },
  tabActiveText: {
    fontSize: px(13),
    fontWeight: '600',
    color: '#FFFFFF',
  },
  posterCard: {
    borderRadius: px(18),
    overflow: 'visible',
    marginBottom: px(15),
  },
  posterImg: {
    borderRadius: px(5),
    marginTop: px(10),
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: px(90),
    marginTop:px(2),
  },
  downloadBtn: {
    flex: 1,
    backgroundColor: '#FF984F',
    borderRadius: px(10),
    paddingVertical: px(12),
    marginRight: px(10),
    marginLeft: px(10),
    alignItems: 'center',
  },
  downloadText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: px(16),
  },
  nextBtn: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: px(10),
    paddingVertical: px(12),
    borderWidth: 1,
    marginRight: px(10),
    marginLeft: px(10),
    alignItems: 'center',
    borderColor: '#ddd',
  },
  nextText: {
    color: '#252525',
    fontWeight: '600',
    fontSize: px(16),
  },
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: px(10),
    right: px(10),
    height: px(80),
    borderRadius: px(50),
    backgroundColor: '#FFF0ED',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#eee',
    marginBottom: px(10),
  },
  navItem: {
    alignItems: 'center',
  },
  iconWrapper: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: px(10),
    padding: px(6),
    marginLeft: px(10),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: px(2),
    elevation: 2,
  },
  iconContainer2: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    borderRadius: px(12),
    padding: px(6),
    marginLeft: px(10),
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: px(2),
    elevation: 2,
  },
  activeIconBg: {
    backgroundColor: '#FF984F',
    borderRadius: px(30),
  },
  navIcon: {
    width: px(32),
    height: px(32),
    marginBottom: px(2),
  },
  navLabel: {
    fontSize: px(12),
    marginTop: px(3),
    fontWeight: '700',
  },
  download: {
    width: px(30),
    height: px(30),
    marginBottom: px(2),
  },
  filterBtn: {
    marginLeft: px(8),
    padding: px(5),
    borderRadius: px(8),
  },
  closeBtnText: {
    color: '#fff',
    textAlign: 'center',
    fontWeight: '600',
  },
  headericon: {
    width: px(20),
    height: px(20),
    // backgroundColor: '#fff',
    // padding: px(13),
  },
  navIconWrapper: {
    justifyContent: 'center',
    alignItems: 'center',
    width: px(26),
    height: px(26),
    borderRadius: px(26),
  },
  activeNavCircle: {
    backgroundColor: '#FF984F',
    elevation: 5,
    borderRadius: px(45),
    padding: px(10),
    width: px(50),
    height: px(50),
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    padding: px(20),
  },
  modalContainer: {
    position: 'absolute',
    bottom: 0,
    width: deviceWidth,
    backgroundColor: 'rgba(255,255,255,0.95)',
    borderTopLeftRadius: px(20),
    borderTopRightRadius: px(20),
    paddingHorizontal: px(20),
    paddingTop: px(15),
    padding: px(60),
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: px(15),
  },
  modalTitle: {
    fontSize: px(24),
    fontWeight: '700',
    color: '#000',
  },
  closeBtn: {
    position: 'absolute',
    top: -px(25),
    right: px(15),
    backgroundColor: '#fff',
    borderRadius: px(25),
    padding: px(10),
    elevation: 5,
  },
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: px(12),
    padding: px(15),
    marginBottom: px(10),
    elevation: 3,
  },
  avatarBorderBox: {
    borderRightWidth: px(3),
    borderBottomWidth: px(3),
    borderColor: '#FF984F',
    borderRadius: px(10),
    padding: px(2),
    marginRight: px(12),
  },
  profileAvatarContainer: {
    borderLeftWidth: px(4),
    borderBottomWidth: px(4),
    borderColor: '#FF984F',
    borderRadius: px(12),
  },
  profileAvatar: {
    width: px(50),
    height: px(50),
    borderRadius: px(10),
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: px(20),
    fontWeight: '700',
    color: '#000',
  },
  profileTag: {
    backgroundColor: '#FF984F',
    paddingHorizontal: px(6),
    paddingVertical: px(2),
    alignSelf: 'flex-start',
    marginTop: px(3),
  },
  profileTagText: {
    color: '#fff',
    fontSize: px(12),
    fontWeight: '500',
  },
  createProfileBtn: {
    backgroundColor: '#FF984F',
    borderRadius: px(8),
    paddingVertical: px(16),
    marginTop: px(90),
    alignItems: 'center',
  },
  createProfileText: {
    color: '#fff',
    fontSize: px(19),
    fontWeight: '600',
  },
  loadingContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: px(40),
  },
  loadingText: {
    marginTop: px(12),
    fontSize: px(16),
    color: '#666',
  },
  templateContainer: {
    alignItems: 'center',
  },
  templateImage: {
    width: deviceWidth,
    height: px(450),
    borderRadius: px(12),
    backgroundColor: '#f5f5f5',
  },
  placeholderImage: {
    width: deviceWidth,
    height: px(200),
    backgroundColor: '#e0e0e0',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: px(12),
  },
  templateInfo: {
    marginTop: px(16),
    width: deviceWidth,
    paddingHorizontal: px(8),
  },
  templateTitle: {
    fontSize: px(20),
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: px(8),
  },
  templateDescription: {
    fontSize: px(14),
    color: '#666',
    textAlign: 'center',
    lineHeight: px(20),
  },
  noTemplateContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: px(40),
  },
  noTemplateText: {
    fontSize: px(16),
    color: '#999',
    textAlign: 'center',
  },
});
// });

